// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class ASDtoServiceRequest;
@class ASDtoServiceRequestBuilder;
@class ASDtoServiceResponse;
@class ASDtoServiceResponseBuilder;
@class ObjectiveCFileOptions;
@class ObjectiveCFileOptionsBuilder;
@class PBDescriptorProto;
@class PBDescriptorProtoBuilder;
@class PBDescriptorProtoExtensionRange;
@class PBDescriptorProtoExtensionRangeBuilder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProtoBuilder;
@class PBEnumOptions;
@class PBEnumOptionsBuilder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProtoBuilder;
@class PBEnumValueOptions;
@class PBEnumValueOptionsBuilder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProtoBuilder;
@class PBFieldOptions;
@class PBFieldOptionsBuilder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProtoBuilder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSetBuilder;
@class PBFileOptions;
@class PBFileOptionsBuilder;
@class PBMessageOptions;
@class PBMessageOptionsBuilder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProtoBuilder;
@class PBMethodOptions;
@class PBMethodOptionsBuilder;
@class PBOneofDescriptorProto;
@class PBOneofDescriptorProtoBuilder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProtoBuilder;
@class PBServiceOptions;
@class PBServiceOptionsBuilder;
@class PBSourceCodeInfo;
@class PBSourceCodeInfoBuilder;
@class PBSourceCodeInfoLocation;
@class PBSourceCodeInfoLocationBuilder;
@class PBUninterpretedOption;
@class PBUninterpretedOptionBuilder;
@class PBUninterpretedOptionNamePart;
@class PBUninterpretedOptionNamePartBuilder;


typedef NS_ENUM(SInt32, ASDtoServiceRequestMode) {
  ASDtoServiceRequestModeTCP = 0,
  ASDtoServiceRequestModeUDP = 1,
};

BOOL ASDtoServiceRequestModeIsValidValue(ASDtoServiceRequestMode value);
NSString *NSStringFromASDtoServiceRequestMode(ASDtoServiceRequestMode value);


@interface ASDtoDiscoveryRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ServiceRequest_type @"type"
#define ServiceRequest_port @"port"
#define ServiceRequest_mode @"mode"
@interface ASDtoServiceRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPort_:1;
  BOOL hasType_:1;
  BOOL hasMode_:1;
  SInt32 port;
  NSString* type;
  ASDtoServiceRequestMode mode;
}
- (BOOL) hasType;
- (BOOL) hasPort;
- (BOOL) hasMode;
@property (readonly, strong) NSString* type;
@property (readonly) SInt32 port;
@property (readonly) ASDtoServiceRequestMode mode;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ASDtoServiceRequestBuilder*) builder;
+ (ASDtoServiceRequestBuilder*) builder;
+ (ASDtoServiceRequestBuilder*) builderWithPrototype:(ASDtoServiceRequest*) prototype;
- (ASDtoServiceRequestBuilder*) toBuilder;

+ (ASDtoServiceRequest*) parseFromData:(NSData*) data;
+ (ASDtoServiceRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ASDtoServiceRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ASDtoServiceRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ASDtoServiceRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ASDtoServiceRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ASDtoServiceRequestBuilder : PBGeneratedMessageBuilder {
@private
  ASDtoServiceRequest* resultServiceRequest;
}

- (ASDtoServiceRequest*) defaultInstance;

- (ASDtoServiceRequestBuilder*) clear;
- (ASDtoServiceRequestBuilder*) clone;

- (ASDtoServiceRequest*) build;
- (ASDtoServiceRequest*) buildPartial;

- (ASDtoServiceRequestBuilder*) mergeFrom:(ASDtoServiceRequest*) other;
- (ASDtoServiceRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ASDtoServiceRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (NSString*) type;
- (ASDtoServiceRequestBuilder*) setType:(NSString*) value;
- (ASDtoServiceRequestBuilder*) clearType;

- (BOOL) hasPort;
- (SInt32) port;
- (ASDtoServiceRequestBuilder*) setPort:(SInt32) value;
- (ASDtoServiceRequestBuilder*) clearPort;

- (BOOL) hasMode;
- (ASDtoServiceRequestMode) mode;
- (ASDtoServiceRequestBuilder*) setMode:(ASDtoServiceRequestMode) value;
- (ASDtoServiceRequestBuilder*) clearMode;
@end

#define ServiceResponse_port @"port"
#define ServiceResponse_type @"type"
#define ServiceResponse_title @"title"
#define ServiceResponse_payload @"payload"
@interface ASDtoServiceResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPort_:1;
  BOOL hasType_:1;
  BOOL hasTitle_:1;
  BOOL hasPayload_:1;
  SInt32 port;
  NSString* type;
  NSString* title;
  NSData* payload;
}
- (BOOL) hasPort;
- (BOOL) hasType;
- (BOOL) hasTitle;
- (BOOL) hasPayload;
@property (readonly) SInt32 port;
@property (readonly, strong) NSString* type;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSData* payload;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ASDtoServiceResponseBuilder*) builder;
+ (ASDtoServiceResponseBuilder*) builder;
+ (ASDtoServiceResponseBuilder*) builderWithPrototype:(ASDtoServiceResponse*) prototype;
- (ASDtoServiceResponseBuilder*) toBuilder;

+ (ASDtoServiceResponse*) parseFromData:(NSData*) data;
+ (ASDtoServiceResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ASDtoServiceResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ASDtoServiceResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ASDtoServiceResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ASDtoServiceResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ASDtoServiceResponseBuilder : PBGeneratedMessageBuilder {
@private
  ASDtoServiceResponse* resultServiceResponse;
}

- (ASDtoServiceResponse*) defaultInstance;

- (ASDtoServiceResponseBuilder*) clear;
- (ASDtoServiceResponseBuilder*) clone;

- (ASDtoServiceResponse*) build;
- (ASDtoServiceResponse*) buildPartial;

- (ASDtoServiceResponseBuilder*) mergeFrom:(ASDtoServiceResponse*) other;
- (ASDtoServiceResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ASDtoServiceResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPort;
- (SInt32) port;
- (ASDtoServiceResponseBuilder*) setPort:(SInt32) value;
- (ASDtoServiceResponseBuilder*) clearPort;

- (BOOL) hasType;
- (NSString*) type;
- (ASDtoServiceResponseBuilder*) setType:(NSString*) value;
- (ASDtoServiceResponseBuilder*) clearType;

- (BOOL) hasTitle;
- (NSString*) title;
- (ASDtoServiceResponseBuilder*) setTitle:(NSString*) value;
- (ASDtoServiceResponseBuilder*) clearTitle;

- (BOOL) hasPayload;
- (NSData*) payload;
- (ASDtoServiceResponseBuilder*) setPayload:(NSData*) value;
- (ASDtoServiceResponseBuilder*) clearPayload;
@end


// @@protoc_insertion_point(global_scope)
